### ISSUE TITLE
Add forget password functionality

### ISSUE THREAD

**Issue by rajankit911** [nevtop/crm-vuejs-app#9]
On clicking forgot password, user should navigate to forget password view
Page: **ForgotPassword.vue**

**Fields Required**
- Enter a username or email: **Header**
- Username or email: **Textbox**
- Send Email: **Button** 

images attached for reference
![forgot step 1](https://user-images.githubusercontent.com/41474587/98103453-06fe9f80-1ebb-11eb-8205-acbe57c5bcf8.png)
![forgot step 2](https://user-images.githubusercontent.com/41474587/98103454-082fcc80-1ebb-11eb-9a2c-f94d2ac8bd3d.png)
![login](https://user-images.githubusercontent.com/41474587/98103456-08c86300-1ebb-11eb-9e01-5755f451518a.png)

**Comment by RajathJ** [comment]
Designed ForgotPassword Page #9
